### PR TITLE
Added animation and skin

### PR DESCRIPTION
**Pull request by mrlooi**
CUBICSPLINE still not implemented

EDIT: Added in latest commit

### CODE REVIEW

**Comment by wnayes** [comment]
Thanks! I will take a look through this shortly.

**Comment by mrlooi** [comment]
Added cubicspline interpolation

**Comment by mrlooi** [comment]
Added skin support

**Comment by wnayes** [comment]
I noticed that some of the original files (buffer.ts etc.) are hard to diff because the file formatting went from 2 spaces to 4 spaces. I would like to maintain consistency with 2 space tabs for now I think, for the purposes of seeing what has changed. Long term I should probably just set up prettier or something like that.

I also think the UMD webpack export is missing? I'm fine with having a demo page and webpack server, but can the UMD output be restored?

**Comment by mrlooi** [comment]
Done. Latest commit reindents to 2 spaces and resets to original webpack.dev.config.js

**Pull request merged**
